pub(crate) mod accelerators;
pub(crate) mod algorithms;
mod bounding_box;
pub(crate) mod camera;
mod closest_primitive;
pub(crate) mod color;
pub mod float;
mod generic_vector;
pub(crate) mod light_source;
pub(crate) mod material;
mod normal;
mod parsers;
pub(crate) mod point;
mod primitives;
mod ray;
pub(crate) mod render_method;
pub(crate) mod renderer;
pub(crate) mod rng;
pub(crate) mod section;
pub(crate) mod solids;
mod trace;
pub(crate) mod transform;
pub(crate) mod vector;
pub(crate) mod world;
