[package]
name = "ilios"
version = "0.1.0"
authors = ["Enrique <niofis@gmail.com>"]
edition = "2018"

[profile.dev]
split-debuginfo = "unpacked"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1.5"