[package]
name = "ilios"
version = "0.1.0"
authors = ["Enrique <niofis@gmail.com>"]
edition = "2018"

[profile.dev]
split-debuginfo = "unpacked"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8"
rayon = "1.5"
tobj = "1.0"
rand_xoshiro = "0.6.0"