mod accelerator;
mod bounding_box;
mod bounding_volume_hierarchy;
mod brute_force;
mod camera;
mod color;
pub(crate) mod demos;
mod direct_illumination;
mod light;
mod material;
mod primitive;
mod ray;
pub(crate) mod renderer;
mod solid;
mod trace;
mod transform;
mod vector;
pub(crate) mod world;
