pub(crate) mod accelerator;
mod bounding_box;
mod bounding_volume_hierarchy;
mod brute_force;
pub(crate) mod camera;
pub(crate) mod color;
mod generic_vector;
pub(crate) mod light_source;
pub(crate) mod material;
mod normal;
mod path_tracing;
mod pixel;
pub(crate) mod point;
mod primitive;
mod ray;
pub(crate) mod renderer;
mod scanline;
pub(crate) mod section;
pub(crate) mod solid;
mod tile;
mod trace;
pub(crate) mod transform;
pub(crate) mod vector;
mod whitted;
pub(crate) mod world;
