pub(crate) mod accelerator;
mod bounding_box;
mod bounding_volume_hierarchy;
mod brute_force;
pub(crate) mod camera;
pub(crate) mod color;
pub(crate) mod light;
pub(crate) mod material;
mod normal;
mod path_tracing;
pub(crate) mod point;
mod primitive;
mod ray;
pub(crate) mod renderer;
pub(crate) mod section;
pub(crate) mod solid;
mod trace;
pub(crate) mod transform;
pub(crate) mod vector;
mod whitted;
pub(crate) mod world;
